# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v4
        with:
          # Ensure we pull down all commits & branches, not just this tag
          fetch-depth: 0
          # Force-checkout "main" or whatever branch you want to push changes to
          ref: main
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn test

      - name: Bump version
        run: |
          # e.g., "v1.2.3"
          FULL_TAG="${{ github.event.release.tag_name }}"
          VERSION="${FULL_TAG#v}"

          # Update version without creating a new tag
          npm version "$VERSION" --allow-same-version --no-git-tag-version

          # Commit + push back to main
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Bump to version $VERSION"
          git push origin HEAD:main

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}